<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>The Complete Journey User Guide • completejourney</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/spacelab/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="The Complete Journey User Guide">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">completejourney</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">0.0.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa fas fa-book"></span>
     
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/completejourney.html">User Guide</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">
    <span class="fa fa-file-code-o"></span>
     
    Reference
  </a>
</li>
<li>
  <a href="../news/index.html">
    <span class="fa fa-newspaper-o"></span>
     
    News
  </a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/bradleyboehmke/completejourney">
    <span class="fa fa-github fa-lg"></span>
     
    GitHub
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>The Complete Journey User Guide</h1>
                        <h4 class="author">Brad Boehmke</h4>
            
            <h4 class="date">2019-04-25</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/bradleyboehmke/completejourney/blob/master/vignettes/completejourney.Rmd"><code>vignettes/completejourney.Rmd</code></a></small>
      <div class="hidden name"><code>completejourney.Rmd</code></div>

    </div>

    
    
<div id="the-complete-journey" class="section level2">
<h2 class="hasAnchor">
<a href="#the-complete-journey" class="anchor"></a>The Complete Journey</h2>
<p>completejourney provides access to data sets characterizing household level transactions over one year from a group of 2,469 households who are frequent shoppers at a grocery store. It contains all of each household’s purchases, not just those from a limited number of categories. For certain households, demographic information as well as direct marketing contact history are captured.</p>
<p>Due to the number of tables and the overall complexity of The Complete Journey, it is suggested that this database be used in more advanced classroom settings. Further, The Complete Journey would be ideal for academic research as it should enable one to study the effects of direct marketing to customers.</p>
<p>The following are examples of questions that could be submitted to students or considered for academic research:</p>
<ul>
<li>How many customers are spending more over time? Less over time? Describe these customers.</li>
<li>Of those customers who are spending more over time, which categories are growing at a faster rate?</li>
<li>Of those customers who are spending less over time, with which categories are they becoming less engaged?</li>
<li>Which demographic factors (e.g. household size, presence of children, income) appear to affect customer spend? Engagement with certain categories?</li>
<li>Is there evidence to suggest that direct marketing improves overall engagement?</li>
</ul>
</div>
<div id="downloading-the-data" class="section level2">
<h2 class="hasAnchor">
<a href="#downloading-the-data" class="anchor"></a>Downloading the Data</h2>
<p>The data sets available through this package are quite sizeable; and too large to be contained within the package. <code><a href="../reference/get_data.html">get_data()</a></code> provides an efficient method for downloading one or more of the data sets from the source GitHub repository.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(completejourney)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw"><a href="../reference/get_data.html">get_data</a></span>(<span class="dt">which =</span> <span class="st">"all"</span>, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<p>Each downloaded data set is saved as a tibble in the users global environment. For specifc details on a given data set see the data sets respective help file (i.e. <code><a href="../reference/transactions.html">?transactions</a></code>).</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="kw">ls</span>()</a>
<a class="sourceLine" id="cb2-2" data-line-number="2"><span class="co">#&gt; [1] "campaign_descriptions" "campaigns"             "coupon_redemptions"   </span></a>
<a class="sourceLine" id="cb2-3" data-line-number="3"><span class="co">#&gt; [4] "coupons"               "demographics"          "products"             </span></a>
<a class="sourceLine" id="cb2-4" data-line-number="4"><span class="co">#&gt; [7] "promotions"            "transactions"</span></a></code></pre></div>
</div>
<div id="dataset-details" class="section level2">
<h2 class="hasAnchor">
<a href="#dataset-details" class="anchor"></a>Dataset Details</h2>
<p><img src="data_relationships.png" width="95%" height="95%"></p>
<div id="demographics" class="section level3">
<h3 class="hasAnchor">
<a href="#demographics" class="anchor"></a><code>demographics</code>
</h3>
<p>This table contains demographic information for a portion of households. Due to nature of the data, the demographic information is not available for all households.</p>
<table class="table">
<thead><tr class="header">
<th>Variable</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>household_id</code></td>
<td>Uniquely identifies each household</td>
</tr>
<tr class="even">
<td><code>age</code></td>
<td>Estimated age range</td>
</tr>
<tr class="odd">
<td><code>income</code></td>
<td>Household income</td>
</tr>
<tr class="even">
<td><code>home_ownership</code></td>
<td>Homeowner, renter, etc.</td>
</tr>
<tr class="odd">
<td><code>marital_status</code></td>
<td>Marital status (Married, Single, Unknown)</td>
</tr>
<tr class="even">
<td><code>household_size</code></td>
<td>Size of household up to 5+</td>
</tr>
<tr class="odd">
<td><code>household_comp</code></td>
<td>Household composition</td>
</tr>
<tr class="even">
<td><code>kid_count</code></td>
<td>Number of children present up to 3+</td>
</tr>
</tbody>
</table>
</div>
<div id="transactions" class="section level3">
<h3 class="hasAnchor">
<a href="#transactions" class="anchor"></a><code>transactions</code>
</h3>
<p>Contains transaction-level product purchases by households (what you would normally see on a receipt).</p>
<table class="table">
<colgroup>
<col width="22%">
<col width="77%">
</colgroup>
<thead><tr class="header">
<th>Variable</th>
<th>Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>household_id</code></td>
<td>Uniquely identifies each household</td>
</tr>
<tr class="even">
<td><code>store_id</code></td>
<td>Uniquely identifies each store</td>
</tr>
<tr class="odd">
<td><code>basket_id</code></td>
<td>Uniquely identifies each purchase occasion</td>
</tr>
<tr class="even">
<td><code>product_id</code></td>
<td>Uniquely identifies each product</td>
</tr>
<tr class="odd">
<td><code>quantity</code></td>
<td>Number of the product purchased during the trip</td>
</tr>
<tr class="even">
<td><code>sales_value</code></td>
<td>Amount of dollars the retailer receives from sale</td>
</tr>
<tr class="odd">
<td><code>retail_disc</code></td>
<td>Discount applied due to the retailer’s loyalty card program</td>
</tr>
<tr class="even">
<td><code>coupon_disc</code></td>
<td>Discount applied due to a manufacturer coupon</td>
</tr>
<tr class="odd">
<td><code>coupon_match_disc</code></td>
<td>Discount applied due to retailer’s match of manufacturer coupon</td>
</tr>
<tr class="even">
<td><code>week</code></td>
<td>Week of the transaction; Ranges 1-53</td>
</tr>
<tr class="odd">
<td><code>transaction_timestamp</code></td>
<td>Date and time of day when the transaction occurred</td>
</tr>
</tbody>
</table>
<p>The variable <code>sales_value</code> in this table is the amount of dollars received by the retailer on the sale of the specific product, taking the coupon match and loyalty card discount into account. It is not the actual price paid by the customer. If a customer uses a coupon, the actual price paid will be less than the <code>sales_value</code> because the manufacturer issuing the coupon will reimburse the retailer for the amount of the coupon.</p>
<p>To calculate the actual product prices, use the formulas below:</p>
<ul>
<li>Loyalty card price = (sales_value – (retail_disc + coupon_match_disc)) / quantity</li>
<li>Non-loyalty card price = (sales_value – (coupon_match_disc)) / quantity</li>
</ul>
<p>The example below demonstrates how to calculate the actual shelf price of the product:</p>
<pre><code>#&gt; # A tibble: 3 x 6
#&gt;   product_id quantity sales_value retail_disc coupon_disc coupon_match_disc
#&gt;   &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;             &lt;dbl&gt;
#&gt; 1 819063            1        1.67        0           0                 0   
#&gt; 2 819063            2        3.34        0.36        0                 0   
#&gt; 3 819063            2        2.89        0           0.55              0.45</code></pre>
<ul>
<li>Line 1 – When this product was purchased the <code>retail_disc</code> and <code>coupon_disc</code> were both zero, meaning the price of the product is the same as the amount received by the retailer.</li>
<li>Line 2 – Two items of this product were purchased, and there was a retail discount applied due to a loyalty card. To determine the regular shelf price of the product (exclusive of loyalty card discount) we take the sum of the amount paid and the discount, then divide it by the quantity (<span class="math inline">\(\$3.34 + \$0.36) \div 2 = \$1.85\)</span>. The shelf price of the product including loyalty card discount is <span class="math inline">\(\$3.34 \div 2 = \$1.67\)</span>. In this case, the customer paid $3.34 for both of these products, which is the same amount the retailer received.</li>
<li>Line 3 – The actual shelf price of each product here is (<span class="math inline">\(\$2.89 + \$0.45) \div 2 = \$1.67\)</span>. In this case, the customer paid $2.34 (<span class="math inline">\(\$2.89 - \$0.55\)</span>) for these products, but the retailer will receive $2.89 due to reimbursement of the manufacturer discount.</li>
</ul>
</div>
<div id="campaigns" class="section level3">
<h3 class="hasAnchor">
<a href="#campaigns" class="anchor"></a><code>campaigns</code>
</h3>
<p>Contains identifying information for the marketing campaigns each households participated in.</p>
<table class="table">
<thead><tr class="header">
<th>Variable</th>
<th>Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>campaign_id</code></td>
<td>Uniquely identifies each campaign; Ranges 1-27</td>
</tr>
<tr class="even">
<td><code>household_id</code></td>
<td>Uniquely identifies each household</td>
</tr>
</tbody>
</table>
</div>
<div id="campaign_descriptions" class="section level3">
<h3 class="hasAnchor">
<a href="#campaign_descriptions" class="anchor"></a><code>campaign_descriptions</code>
</h3>
<p>Contains campaign metatdata, specifically the time a campaign was active.</p>
<table class="table">
<thead><tr class="header">
<th>Variable</th>
<th>Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>campaign_id</code></td>
<td>Uniquely identifies each campaign; Ranges 1-27</td>
</tr>
<tr class="even">
<td><code>campaign_type</code></td>
<td>Type of campaign (Type A, Type B, Type C)</td>
</tr>
<tr class="odd">
<td><code>start_date</code></td>
<td>Start date of campaign</td>
</tr>
<tr class="even">
<td><code>end_date</code></td>
<td>End date of campaign</td>
</tr>
</tbody>
</table>
</div>
<div id="products" class="section level3">
<h3 class="hasAnchor">
<a href="#products" class="anchor"></a><code>products</code>
</h3>
<p>Contains metatdata regarding the products purchased (brand, description, etc.).</p>
<table class="table">
<thead><tr class="header">
<th>Variable</th>
<th>Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>product_id</code></td>
<td>Uniquely identifies each product</td>
</tr>
<tr class="even">
<td><code>manufacturer_id</code></td>
<td>Uniquely identifies each manufacturer</td>
</tr>
<tr class="odd">
<td><code>department</code></td>
<td>Groups similar products together</td>
</tr>
<tr class="even">
<td><code>brand</code></td>
<td>Indicates private or national label brand</td>
</tr>
<tr class="odd">
<td><code>product_category</code></td>
<td>Groups similar products together at lower level</td>
</tr>
<tr class="even">
<td><code>product_type</code></td>
<td>Groups similar products together at lowest level</td>
</tr>
<tr class="odd">
<td><code>package_size</code></td>
<td>Indicates package size (not available for all products)</td>
</tr>
</tbody>
</table>
</div>
<div id="coupons" class="section level3">
<h3 class="hasAnchor">
<a href="#coupons" class="anchor"></a><code>coupons</code>
</h3>
<p>This table lists all the coupons sent to customers as part of a campaign, as well as the products for which each coupon is redeemable. Some coupons are redeemable for multiple products. One example is a coupon for any private label frozen vegetable. There are a large number of products where this coupon could be redeemed.</p>
<p>For campaign TypeA, this table provides the pool of possible coupons. Each customer participating in a Type A campaign received 16 coupons out of the pool. The 16 coupons were selected based on the customer’s prior purchase behavior. Identifying the specific 16 coupons that each customer received is outside the scope of this database.</p>
<p>For campaign Type B and Type C, all customers participating in a campaign receives all coupons pertaining to that campaign.</p>
<table class="table">
<colgroup>
<col width="22%">
<col width="77%">
</colgroup>
<thead><tr class="header">
<th>Variable</th>
<th>Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>coupon_upc</code></td>
<td>Uniquely identifies each coupon (unique to household and campaign)</td>
</tr>
<tr class="even">
<td><code>product_id</code></td>
<td>Uniquely identifies each product</td>
</tr>
<tr class="odd">
<td><code>campaign_id</code></td>
<td>Uniquely identifies each campaign</td>
</tr>
</tbody>
</table>
</div>
<div id="coupon_redemptions" class="section level3">
<h3 class="hasAnchor">
<a href="#coupon_redemptions" class="anchor"></a><code>coupon_redemptions</code>
</h3>
<p>Contains individual coupon redemptions (household, day, UPC code, campaign) that can be used to measure campaign efficacy and coupon usage on specific products.</p>
<table class="table">
<colgroup>
<col width="22%">
<col width="77%">
</colgroup>
<thead><tr class="header">
<th>Variable</th>
<th>Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>household_id</code></td>
<td>Uniquely identifies each household</td>
</tr>
<tr class="even">
<td><code>coupon_upc</code></td>
<td>Uniquely identifies each coupon (unique to household and campaign)</td>
</tr>
<tr class="odd">
<td><code>campaign_id</code></td>
<td>Uniquely identifies each campaign</td>
</tr>
<tr class="even">
<td><code>redemption_date</code></td>
<td>Date when the coupon was redeemed</td>
</tr>
</tbody>
</table>
</div>
<div id="promotions" class="section level3">
<h3 class="hasAnchor">
<a href="#promotions" class="anchor"></a><code>promotions</code>
</h3>
<p>Contains product placement information (e.g. mailer page placement and in-store display placement) corresponding to campaigns.</p>
<table class="table">
<colgroup>
<col width="22%">
<col width="77%">
</colgroup>
<thead><tr class="header">
<th>Variable</th>
<th>Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>product_id</code></td>
<td>Uniquely identifies each product</td>
</tr>
<tr class="even">
<td><code>store_id</code></td>
<td>Uniquely identifies each store</td>
</tr>
<tr class="odd">
<td><code>display_location</code></td>
<td>Display location (0-display, 1-store front, 2-store rear, 3-front end cap, 4-mid-aisle end cap, 5-rear end cap, 6-side aisle end cap, 7-in-aisle, 9-secondary location display, A-in-shelf)</td>
</tr>
<tr class="even">
<td><code>mailer_location</code></td>
<td>Mailer location (0-not on ad, A-interior page feature, C-interior page line item, D-front page feature, F-back page feature, H-wrap front feature, J-wrap interior coupon, L-wrap back feature, P-interior page coupon, X-free on interior page, Z-free on front page, back page, or wrap)</td>
</tr>
<tr class="odd">
<td><code>week</code></td>
<td>Week of the transaction; Ranges 1-53</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="example-case-study" class="section level2">
<h2 class="hasAnchor">
<a href="#example-case-study" class="anchor"></a>Example Case Study</h2>
<p>John Smith is a valued customer at a national grocery retailer for which we have detailed transaction data. Throughout all the tables in the database, he is identified with a <code>household_id</code> of “208”.</p>
<p>To learn a little about John, we can obtain his demographic information by looking at the record in the <code>demographics</code> table where <code>household_id = "208"</code>. The table below shows the information we receive, and tells us that he is a homeowner, who makes between $50,000 and $74,000 a year and is between 45 and 54 years old.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">demographics <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb4-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(household_id <span class="op">==</span><span class="st"> "208"</span>)</a>
<a class="sourceLine" id="cb4-3" data-line-number="3"><span class="co">#&gt; # A tibble: 1 x 8</span></a>
<a class="sourceLine" id="cb4-4" data-line-number="4"><span class="co">#&gt;   household_id age   income home_ownership marital_status household_size</span></a>
<a class="sourceLine" id="cb4-5" data-line-number="5"><span class="co">#&gt;   &lt;chr&gt;        &lt;ord&gt; &lt;ord&gt;  &lt;ord&gt;          &lt;ord&gt;          &lt;ord&gt;         </span></a>
<a class="sourceLine" id="cb4-6" data-line-number="6"><span class="co">#&gt; 1 208          45-54 50-74K Homeowner      &lt;NA&gt;           2             </span></a>
<a class="sourceLine" id="cb4-7" data-line-number="7"><span class="co">#&gt; # … with 2 more variables: household_comp &lt;ord&gt;, kids_count &lt;ord&gt;</span></a></code></pre></div>
<p>If we look at John’s records from <code>campaigns</code>, we can see that he received 7 different campaigns.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">campaigns <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb5-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(household_id <span class="op">==</span><span class="st"> "208"</span>)</a>
<a class="sourceLine" id="cb5-3" data-line-number="3"><span class="co">#&gt; # A tibble: 7 x 2</span></a>
<a class="sourceLine" id="cb5-4" data-line-number="4"><span class="co">#&gt;   campaign_id household_id</span></a>
<a class="sourceLine" id="cb5-5" data-line-number="5"><span class="co">#&gt;   &lt;chr&gt;       &lt;chr&gt;       </span></a>
<a class="sourceLine" id="cb5-6" data-line-number="6"><span class="co">#&gt; 1 13          208         </span></a>
<a class="sourceLine" id="cb5-7" data-line-number="7"><span class="co">#&gt; 2 17          208         </span></a>
<a class="sourceLine" id="cb5-8" data-line-number="8"><span class="co">#&gt; 3 18          208         </span></a>
<a class="sourceLine" id="cb5-9" data-line-number="9"><span class="co">#&gt; 4 22          208         </span></a>
<a class="sourceLine" id="cb5-10" data-line-number="10"><span class="co">#&gt; 5 26          208         </span></a>
<a class="sourceLine" id="cb5-11" data-line-number="11"><span class="co">#&gt; 6 27          208         </span></a>
<a class="sourceLine" id="cb5-12" data-line-number="12"><span class="co">#&gt; 7 8           208</span></a></code></pre></div>
<p>These campaigns were spread out over the one year period of the study. To understand the time periods and types of these campaigns, you can join with the <code>campaign_descriptions</code> data. In this example, we see the type of campaign along with the start and end dates of the campaign.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1">campaigns <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb6-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(household_id <span class="op">==</span><span class="st"> "208"</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb6-3" data-line-number="3"><span class="st">  </span><span class="kw">left_join</span>(., campaign_descriptions, <span class="dt">by=</span><span class="st">"campaign_id"</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb6-4" data-line-number="4"><span class="st">  </span><span class="kw">arrange</span>(start_date)</a>
<a class="sourceLine" id="cb6-5" data-line-number="5"><span class="co">#&gt; # A tibble: 7 x 5</span></a>
<a class="sourceLine" id="cb6-6" data-line-number="6"><span class="co">#&gt;   campaign_id household_id campaign_type start_date end_date  </span></a>
<a class="sourceLine" id="cb6-7" data-line-number="7"><span class="co">#&gt;   &lt;chr&gt;       &lt;chr&gt;        &lt;ord&gt;         &lt;date&gt;     &lt;date&gt;    </span></a>
<a class="sourceLine" id="cb6-8" data-line-number="8"><span class="co">#&gt; 1 26          208          Type B        2016-12-28 2017-02-19</span></a>
<a class="sourceLine" id="cb6-9" data-line-number="9"><span class="co">#&gt; 2 27          208          Type A        2017-02-08 2017-03-26</span></a>
<a class="sourceLine" id="cb6-10" data-line-number="10"><span class="co">#&gt; 3 8           208          Type A        2017-05-08 2017-06-25</span></a>
<a class="sourceLine" id="cb6-11" data-line-number="11"><span class="co">#&gt; 4 13          208          Type A        2017-08-08 2017-09-24</span></a>
<a class="sourceLine" id="cb6-12" data-line-number="12"><span class="co">#&gt; 5 17          208          Type B        2017-10-18 2017-11-19</span></a>
<a class="sourceLine" id="cb6-13" data-line-number="13"><span class="co">#&gt; 6 18          208          Type A        2017-10-30 2017-12-24</span></a>
<a class="sourceLine" id="cb6-14" data-line-number="14"><span class="co">#&gt; 7 22          208          Type B        2017-12-06 2018-01-07</span></a></code></pre></div>
<p>Let us take a closer look at campaign 18 When we look at all the distinct coupon_upc’s from the coupon table where <code>campaign_id = "18"</code>, we see that there were 209 distinct coupons sent out as part of that campaign.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">coupons <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb7-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(campaign_id <span class="op">==</span><span class="st"> "18"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb7-3" data-line-number="3"><span class="st">  </span><span class="kw">distinct</span>(coupon_upc)</a>
<a class="sourceLine" id="cb7-4" data-line-number="4"><span class="co">#&gt; # A tibble: 209 x 1</span></a>
<a class="sourceLine" id="cb7-5" data-line-number="5"><span class="co">#&gt;    coupon_upc </span></a>
<a class="sourceLine" id="cb7-6" data-line-number="6"><span class="co">#&gt;    &lt;chr&gt;      </span></a>
<a class="sourceLine" id="cb7-7" data-line-number="7"><span class="co">#&gt;  1 10000085475</span></a>
<a class="sourceLine" id="cb7-8" data-line-number="8"><span class="co">#&gt;  2 10000085476</span></a>
<a class="sourceLine" id="cb7-9" data-line-number="9"><span class="co">#&gt;  3 10000085477</span></a>
<a class="sourceLine" id="cb7-10" data-line-number="10"><span class="co">#&gt;  4 10000085478</span></a>
<a class="sourceLine" id="cb7-11" data-line-number="11"><span class="co">#&gt;  5 10000085479</span></a>
<a class="sourceLine" id="cb7-12" data-line-number="12"><span class="co">#&gt;  6 10000085480</span></a>
<a class="sourceLine" id="cb7-13" data-line-number="13"><span class="co">#&gt;  7 10000085484</span></a>
<a class="sourceLine" id="cb7-14" data-line-number="14"><span class="co">#&gt;  8 10000089237</span></a>
<a class="sourceLine" id="cb7-15" data-line-number="15"><span class="co">#&gt;  9 10000089238</span></a>
<a class="sourceLine" id="cb7-16" data-line-number="16"><span class="co">#&gt; 10 10000089239</span></a>
<a class="sourceLine" id="cb7-17" data-line-number="17"><span class="co">#&gt; # … with 199 more rows</span></a></code></pre></div>
<p>Let us take an even deeper look at one of the specific coupons offered as part of the campaign. If we print out all records from the coupon table where <code>campaign_id = "18"</code> and <code>coupon_upc = "55410000076"</code>, we see that this coupon could actually be redeemed for a number of products.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">coupons <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(campaign_id <span class="op">==</span><span class="st"> "18"</span>, </a>
<a class="sourceLine" id="cb8-3" data-line-number="3">         coupon_upc <span class="op">==</span><span class="st"> "55410000076"</span>)</a>
<a class="sourceLine" id="cb8-4" data-line-number="4"><span class="co">#&gt; # A tibble: 50 x 3</span></a>
<a class="sourceLine" id="cb8-5" data-line-number="5"><span class="co">#&gt;    coupon_upc  product_id campaign_id</span></a>
<a class="sourceLine" id="cb8-6" data-line-number="6"><span class="co">#&gt;    &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;      </span></a>
<a class="sourceLine" id="cb8-7" data-line-number="7"><span class="co">#&gt;  1 55410000076 1004458    18         </span></a>
<a class="sourceLine" id="cb8-8" data-line-number="8"><span class="co">#&gt;  2 55410000076 1011841    18         </span></a>
<a class="sourceLine" id="cb8-9" data-line-number="9"><span class="co">#&gt;  3 55410000076 1016495    18         </span></a>
<a class="sourceLine" id="cb8-10" data-line-number="10"><span class="co">#&gt;  4 55410000076 10182852   18         </span></a>
<a class="sourceLine" id="cb8-11" data-line-number="11"><span class="co">#&gt;  5 55410000076 1018696    18         </span></a>
<a class="sourceLine" id="cb8-12" data-line-number="12"><span class="co">#&gt;  6 55410000076 1058591    18         </span></a>
<a class="sourceLine" id="cb8-13" data-line-number="13"><span class="co">#&gt;  7 55410000076 1065032    18         </span></a>
<a class="sourceLine" id="cb8-14" data-line-number="14"><span class="co">#&gt;  8 55410000076 1069973    18         </span></a>
<a class="sourceLine" id="cb8-15" data-line-number="15"><span class="co">#&gt;  9 55410000076 107157     18         </span></a>
<a class="sourceLine" id="cb8-16" data-line-number="16"><span class="co">#&gt; 10 55410000076 1110721    18         </span></a>
<a class="sourceLine" id="cb8-17" data-line-number="17"><span class="co">#&gt; # … with 40 more rows</span></a></code></pre></div>
<p>Although all the products are not displayed above, we find that this coupon is actually valid on 50 distinct products. If we go to the product table and print out all records for the <code>product_id</code>’s above (“1004458”, “1011841”, etc.), we see that this coupon is valid for pickles from a national brand.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1">coupons <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(campaign_id <span class="op">==</span><span class="st"> "18"</span>, </a>
<a class="sourceLine" id="cb9-3" data-line-number="3">         coupon_upc <span class="op">==</span><span class="st"> "55410000076"</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-4" data-line-number="4"><span class="st">  </span><span class="kw">left_join</span>(., products, <span class="dt">by=</span><span class="st">"product_id"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb9-5" data-line-number="5"><span class="st">  </span><span class="kw">select</span>(product_id, manufacturer_id, department, brand, </a>
<a class="sourceLine" id="cb9-6" data-line-number="6">         product_category, product_type, package_size)</a>
<a class="sourceLine" id="cb9-7" data-line-number="7"><span class="co">#&gt; # A tibble: 50 x 7</span></a>
<a class="sourceLine" id="cb9-8" data-line-number="8"><span class="co">#&gt;    product_id manufacturer_id department brand product_category</span></a>
<a class="sourceLine" id="cb9-9" data-line-number="9"><span class="co">#&gt;    &lt;chr&gt;      &lt;chr&gt;           &lt;chr&gt;      &lt;fct&gt; &lt;chr&gt;           </span></a>
<a class="sourceLine" id="cb9-10" data-line-number="10"><span class="co">#&gt;  1 1004458    1318            GROCERY    Nati… PICKLE/RELISH/P…</span></a>
<a class="sourceLine" id="cb9-11" data-line-number="11"><span class="co">#&gt;  2 1011841    1318            GROCERY    Nati… PICKLE/RELISH/P…</span></a>
<a class="sourceLine" id="cb9-12" data-line-number="12"><span class="co">#&gt;  3 1016495    1318            GROCERY    Nati… PICKLE/RELISH/P…</span></a>
<a class="sourceLine" id="cb9-13" data-line-number="13"><span class="co">#&gt;  4 10182852   1318            GROCERY    Nati… PICKLE/RELISH/P…</span></a>
<a class="sourceLine" id="cb9-14" data-line-number="14"><span class="co">#&gt;  5 1018696    1318            GROCERY    Nati… PICKLE/RELISH/P…</span></a>
<a class="sourceLine" id="cb9-15" data-line-number="15"><span class="co">#&gt;  6 1058591    1318            GROCERY    Nati… PICKLE/RELISH/P…</span></a>
<a class="sourceLine" id="cb9-16" data-line-number="16"><span class="co">#&gt;  7 1065032    1318            GROCERY    Nati… PICKLE/RELISH/P…</span></a>
<a class="sourceLine" id="cb9-17" data-line-number="17"><span class="co">#&gt;  8 1069973    1318            GROCERY    Nati… PICKLE/RELISH/P…</span></a>
<a class="sourceLine" id="cb9-18" data-line-number="18"><span class="co">#&gt;  9 107157     1318            GROCERY    Nati… PICKLE/RELISH/P…</span></a>
<a class="sourceLine" id="cb9-19" data-line-number="19"><span class="co">#&gt; 10 1110721    1318            GROCERY    Nati… PICKLE/RELISH/P…</span></a>
<a class="sourceLine" id="cb9-20" data-line-number="20"><span class="co">#&gt; # … with 40 more rows, and 2 more variables: product_type &lt;chr&gt;,</span></a>
<a class="sourceLine" id="cb9-21" data-line-number="21"><span class="co">#&gt; #   package_size &lt;chr&gt;</span></a></code></pre></div>
<p>As we’ve seen, John received a number of campaigns over the past year that contained many coupons. Chances are, he did not redeem every coupon he received. So, let us take a look to see what coupons he did redeem. To do this, we need to view all records from the <code>coupon_redemptions</code> table where <code>household_id = "208"</code>. This shows us that he redeemed five coupons from two of the campaigns (“8” and “18”).</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">coupon_redemptions <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb10-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(household_id <span class="op">==</span><span class="st"> "208"</span>)</a>
<a class="sourceLine" id="cb10-3" data-line-number="3"><span class="co">#&gt; # A tibble: 5 x 4</span></a>
<a class="sourceLine" id="cb10-4" data-line-number="4"><span class="co">#&gt;   household_id coupon_upc  campaign_id redemption_date</span></a>
<a class="sourceLine" id="cb10-5" data-line-number="5"><span class="co">#&gt;   &lt;chr&gt;        &lt;chr&gt;       &lt;chr&gt;       &lt;date&gt;         </span></a>
<a class="sourceLine" id="cb10-6" data-line-number="6"><span class="co">#&gt; 1 208          55100090033 8           2017-05-23     </span></a>
<a class="sourceLine" id="cb10-7" data-line-number="7"><span class="co">#&gt; 2 208          51800015050 18          2017-11-09     </span></a>
<a class="sourceLine" id="cb10-8" data-line-number="8"><span class="co">#&gt; 3 208          51920021576 18          2017-11-09     </span></a>
<a class="sourceLine" id="cb10-9" data-line-number="9"><span class="co">#&gt; 4 208          55410000076 18          2017-11-13     </span></a>
<a class="sourceLine" id="cb10-10" data-line-number="10"><span class="co">#&gt; 5 208          10000085475 18          2017-11-18</span></a></code></pre></div>
<p>John’s coupon redemptions are only part of the overall picture of his purchasing behavior. If we look at the records from the transaction_data table where <code>household_id = "208"</code>, we can view everything that John purchased.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">transactions <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb11-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(household_id <span class="op">==</span><span class="st"> "208"</span>)</a>
<a class="sourceLine" id="cb11-3" data-line-number="3"><span class="co">#&gt; # A tibble: 756 x 11</span></a>
<a class="sourceLine" id="cb11-4" data-line-number="4"><span class="co">#&gt;    household_id store_id basket_id product_id quantity sales_value</span></a>
<a class="sourceLine" id="cb11-5" data-line-number="5"><span class="co">#&gt;    &lt;chr&gt;        &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;</span></a>
<a class="sourceLine" id="cb11-6" data-line-number="6"><span class="co">#&gt;  1 208          327      31268866… 845379            1        7.64</span></a>
<a class="sourceLine" id="cb11-7" data-line-number="7"><span class="co">#&gt;  2 208          327      31268866… 854133            1        4.69</span></a>
<a class="sourceLine" id="cb11-8" data-line-number="8"><span class="co">#&gt;  3 208          327      31268866… 862349            1        1   </span></a>
<a class="sourceLine" id="cb11-9" data-line-number="9"><span class="co">#&gt;  4 208          327      31268866… 879504            1        2   </span></a>
<a class="sourceLine" id="cb11-10" data-line-number="10"><span class="co">#&gt;  5 208          327      31268866… 990519            1        1.69</span></a>
<a class="sourceLine" id="cb11-11" data-line-number="11"><span class="co">#&gt;  6 208          327      31268866… 1068830           1        1.09</span></a>
<a class="sourceLine" id="cb11-12" data-line-number="12"><span class="co">#&gt;  7 208          327      31268866… 1097635           1        2.96</span></a>
<a class="sourceLine" id="cb11-13" data-line-number="13"><span class="co">#&gt;  8 208          324      31344175… 883932            1        2   </span></a>
<a class="sourceLine" id="cb11-14" data-line-number="14"><span class="co">#&gt;  9 208          324      31344175… 885290            1        1.99</span></a>
<a class="sourceLine" id="cb11-15" data-line-number="15"><span class="co">#&gt; 10 208          324      31344175… 915502            2        4   </span></a>
<a class="sourceLine" id="cb11-16" data-line-number="16"><span class="co">#&gt; # … with 746 more rows, and 5 more variables: retail_disc &lt;dbl&gt;,</span></a>
<a class="sourceLine" id="cb11-17" data-line-number="17"><span class="co">#&gt; #   coupon_disc &lt;dbl&gt;, coupon_match_disc &lt;dbl&gt;, week &lt;int&gt;,</span></a>
<a class="sourceLine" id="cb11-18" data-line-number="18"><span class="co">#&gt; #   transaction_timestamp &lt;dttm&gt;</span></a></code></pre></div>
<p>This gets a bit complicated, but we can combine the transaction data with the other tables to understand John’s behavior when he was redeeming a coupon (and when he wasn’t redeeming a coupon).</p>
<ul>
<li>John received offers as part of campaign 18, which occurred between 10/30/2017 and 12/24/2017</li>
<li>We know he redeemed <code>coupon_upc = "55410000076"</code> on day 11/13/2017</li>
<li>Through the coupon table, we know that the coupon is actually valid for a number of products, including <code>product_id = "896292"</code>
</li>
<li>From the table below, we can see where John purchased this item and received a $1 discount from using the coupon.</li>
</ul>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1">transactions <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb12-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(household_id <span class="op">==</span><span class="st"> "208"</span>, </a>
<a class="sourceLine" id="cb12-3" data-line-number="3">         product_id <span class="op">==</span><span class="st"> "896292"</span>,</a>
<a class="sourceLine" id="cb12-4" data-line-number="4">         <span class="kw">as_date</span>(transaction_timestamp) <span class="op">==</span><span class="st"> "2017-11-13"</span>)</a>
<a class="sourceLine" id="cb12-5" data-line-number="5"><span class="co">#&gt; # A tibble: 1 x 11</span></a>
<a class="sourceLine" id="cb12-6" data-line-number="6"><span class="co">#&gt;   household_id store_id basket_id product_id quantity sales_value</span></a>
<a class="sourceLine" id="cb12-7" data-line-number="7"><span class="co">#&gt;   &lt;chr&gt;        &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;</span></a>
<a class="sourceLine" id="cb12-8" data-line-number="8"><span class="co">#&gt; 1 208          327      40715247… 896292            2           4</span></a>
<a class="sourceLine" id="cb12-9" data-line-number="9"><span class="co">#&gt; # … with 5 more variables: retail_disc &lt;dbl&gt;, coupon_disc &lt;dbl&gt;,</span></a>
<a class="sourceLine" id="cb12-10" data-line-number="10"><span class="co">#&gt; #   coupon_match_disc &lt;dbl&gt;, week &lt;int&gt;, transaction_timestamp &lt;dttm&gt;</span></a></code></pre></div>
<p>Knowing when John redeemed a coupon can help us learn a lot about him, and how the receipt of certain campaigns affected his behavior. Does the receipt of campaigns cause him to purchase more items than he did previously? Is John more likely to redeem coupons for products he already purchases, or does it entice him to try products he has never purchased before?</p>
<p>There is one bit of information we have not talked about yet – what is happening in the rest of the store? Is it possible that John purchased the item above because of other events occurring in the store in addition to his coupon?</p>
<p>We obviously do not know a customer’s reason for purchasing an item, but we do know whether an item was featured during the time of the purchase. If we view all records from the <code>promotions</code> table where <code>product_id = "896292"</code>, we see the weeks and stores where this product was featured in the weekly mailer and whether it was featured as part of an in-store display. If we look at the first line, we can tell that in store 327 and week 47, the product was on the shelf (i.e. <code>display_location="A"</code>) so it was not part of a special display. We can assume this was not an impulse buy because of a display or advertisement. He most likely went to the store with the coupon intent upon purchasing the item.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">promotions <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb13-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(product_id <span class="op">==</span><span class="st"> "896292"</span>, </a>
<a class="sourceLine" id="cb13-3" data-line-number="3">         store_id <span class="op">==</span><span class="st"> "327"</span>)</a>
<a class="sourceLine" id="cb13-4" data-line-number="4"><span class="co">#&gt; # A tibble: 2 x 5</span></a>
<a class="sourceLine" id="cb13-5" data-line-number="5"><span class="co">#&gt;   product_id store_id display_location mailer_location  week</span></a>
<a class="sourceLine" id="cb13-6" data-line-number="6"><span class="co">#&gt;   &lt;chr&gt;      &lt;chr&gt;    &lt;fct&gt;            &lt;fct&gt;           &lt;int&gt;</span></a>
<a class="sourceLine" id="cb13-7" data-line-number="7"><span class="co">#&gt; 1 896292     327      A                0                  47</span></a>
<a class="sourceLine" id="cb13-8" data-line-number="8"><span class="co">#&gt; 2 896292     327      A                0                  49</span></a></code></pre></div>
<p>We hope that this quick look at John Smith’s behavior provides clarity around The Complete Journey database, and inspires your own investigation into the purchasing behavior of these customers.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#the-complete-journey">The Complete Journey</a></li>
      <li><a href="#downloading-the-data">Downloading the Data</a></li>
      <li><a href="#dataset-details">Dataset Details</a></li>
      <li><a href="#example-case-study">Example Case Study</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Brad Boehmke, Steven M. Mortimer.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
